### PR TITLE
Performance optimizations

### PR DESCRIPTION
**Pull request by jonicious**

### CODE REVIEW

**Comment by weiland** [comment]
+1

**Comment by lkstz** [comment]
+1

**Comment by martinwolf** [comment]
Hej @jonicious!

Thanks for your work and pull request.
It's awesome! I only think putting picturefill into the main big scripts.js isn't the way to go and I don't think there is much to gain with the Critical CSS because almost anything is critical. We could just put the complete CSS into the site.

Can you tell me a little bit more about the caching changes you did to the .htaccess?

Cheers!

**Comment by jonicious** [comment]
Why not putting picturefill into the main js file? Currently it is placed in `<head>` and blocks rendering the page. Having it in an extra file, increases the amount of load time and requests. By putting everything in one file, you may not decrease the size of the files but decrease the number of requests which is very important.

Though using Critical CSS only saves some kb, it is worth it, especially on mobile devices with slow internet connection (in developing countries like Germany). Putting the complete CSS into `<head>` is no good style and does not help reaching our goal here.

Apparently, your .htaccess does not work as far as PageSpeed Insights says.
screenshot 2015-02-16 14 31 19

I first add all types I want deflate compression for. Then I am setting the expire dates for every file type and setting the right Header. `Header set Cache-Control "max-age=2592000, public"`

**Comment by martinwolf** [comment]
You are absolutely right, putting everything into one script file is the right way to go and that's what I do with everything except the picturefill file, because I want the polyfill to work as soon as possible for the browsers which not natively support srcset/sizes at the moment. If I load the polyfill with the rest of the JS at the end of the page it can cause trouble/poor visual effects  in certain browsers. At least that's what I've experienced in the past.

Yep, I know what Cirtical CSS is for and what it's trying to solve. I just think that with such a small one-pager there is almost no CSS that is not critical and therefore one could put everything into the page.

Interesting that the .htaccess doesn't work. I once grabbed the caching instructions from HTML5 Boilerplate. I'll try your version, tho.

Thanks for your work!

**Comment by jonicious** [comment]
When will this be live?

**Comment by martinwolf** [comment]
I did a few adjustments and the changes are no live. Thanks! 👍

**Pull request merged**
